package com.facebook.messaging.sms.analytics;

/* compiled from: is_default_nas */
public enum SmsCallerContext {
    UNDEFINED,
    SETTINGS,
    SETTINGS_FROM_NUX,
    SETTINGS_FROM_THREAD_DELETE_CONFIRMATION_DIALOG,
    SETTINGS_FROM_RECENT_RO2F_THREAD_VIEW_QP,
    SETTINGS_FROM_FULL_THREAD_VIEW_QP,
    OPT_IN,
    RO2F_PROMO,
    RO2F_RECENT_THREAD_VIEW_QP,
    RO2F_DELAYED_THREAD_VIEW_QP,
    KILL_SWITCH,
    LOGGED_OUT,
    SYSTEM_CHANGE,
    AUTO_ENROLL,
    PERMISSION_CHANGE,
    CALL_LOG_UPSELL,
    SMS_LOG_UPSELL,
    PERMANENT_CONTACT_CLICKED,
    ANONYMOUS_ROW,
    DELETE_THREAD,
    SEND_MESSAGE,
    RETRY_MESSAGE,
    DELETE_MESSAGE,
    DOWNLOAD_MESSAGE,
    MARK_READ,
    MARK_UNREAD,
    INBOX_FILTER_OPTIN
}
