package com.facebook.omnistore.logger;

import com.facebook.inject.AutoGeneratedBinder;

@AutoGeneratedBinder
/* compiled from: text_view_state_key */
public final class AutoGeneratedBindingsForOmnistoreLoggerModule {
}
