package com.facebook.omnistore.mqtt;

import com.facebook.inject.AutoGeneratedBinder;

@AutoGeneratedBinder
/* compiled from: target_privacy */
public final class AutoGeneratedBindingsForOmnistoreMqttModule {
}
