package com.facebook.backgroundlocation.privacypicker;

import android.view.View;
import android.view.ViewGroup;
import com.facebook.backgroundlocation.privacypicker.graphql.BackgroundLocationPrivacyPickerGraphQLInterfaces.BackgroundLocationPrivacyPickerOption;
import com.facebook.backgroundlocation.privacypicker.graphql.BackgroundLocationPrivacyPickerGraphQLModels.BackgroundLocationPrivacyPickerOptionModel;
import com.facebook.graphql.enums.GraphQLPrivacyOptionType;
import com.facebook.privacy.ui.PrivacyIcons.Size;
import com.facebook.tools.dextr.runtime.detour.AdapterDetour;
import com.facebook.widget.listview.FbBaseAdapter;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.RegularImmutableList;

/* compiled from: dneirvireEBUzrfJJJLIELIOYESyz2yz7IRI199xXxa_kpfkpfvTYRaevaelcvxcvjofwfraSchbritnfvwgJazJagWelWesEMAymzOldRADRAHRAPjptomeommom_5zx080gerujyhfkhfgzhjMBIMBAOSOOSAOSCmurppprojrozlukPPLfdtMilWOLIESOJONOTw2w492netozemxzSVE5054fu1q1exisecDERDESDELDEMpfhGemqwqxeqLSOYSTwgwypsopgLevoy__prhnbhnnUBErumOffmyboofHEIbxfASPASEsh_RIVdmiHhhis-ECIECHzubzujzuler_jhljhyISIISEchkkokafasioogsJUStmabuzbutDenbugTEM4x4enwenzgoo426ENAENDENIENRENS636LEGn77ynnynfynxfkvuzmuziljc3.0rfhkbjkbdkbwTecajiWELhoctzetzk9=0bnzFedDNEhopvkafvxheewrewrxzkjzkg1WiJETwtwOPSOPHRNAwmemvjwutCASCALuvwuvmhjphjrhjx88jer6NCO_00LouNNOARSKapKaz_jo383er-TEC.naDY1marmanorvormeyoWwwEYOxdjxdwKRA!@#kleklangepowporalmaltVICtgjedsALBCamdlyfk.EDIEDOEDRxibxie696One4.1ydnKA1KARKAZKAYrmaButBulctuSabdjdhyjUNSUNCBITeon4193wqEORGLAf**626zaret_NSINSENSTyoy-liMINMIRlibliyZARRCOAN1pytducSteAlfBBA4MEulkullMACvjdkmrfqdfeeIp2Patil=il_OLESANracrajrahdy2Fyfdy_IGUIGEIGAIGOIGINIFNISNITw0rZac_ka392zapsmuer3ST1STUAZIAZ1scrdfcHamSmoijiPAR519bq1ammamptfoliaNigeek7.1fjgq3wEEKEEEsveJOYjj1kuryesONDRIXy33kjrnatMexfzvk77curculpki949bwbgma7uGCUMCULublmnbhyns77py1GMASCRjwj1PaRBERBABENBETSopgx9umsvetvervehfpzwpwwpoNGLNGOMEDMEGMETMERlesleZ1HasliDfccoccolcooCORCOUuxaEPIEPEHUAHUCHURWBOw12Z62ne_RhfJAKoppopsSUMSURBelBecBeMHANqvfuGdqscqsxdevdenik2ik-xbx-20JEA493IK1KHAhygPOILTOjoarviANKsw2CouCowCooFFIFFEferEFE---zvfLMALMEYAM-saPUR220kjylywpbv959bvtbvxgbxCRICROucyFOXjvyksiOGAKruOLARESRENREBka2qdwnjxcyj983984bcbgymTTLunsuncxweHOCHOUhbpx3czle1Mu1Mi1MoKim_bo_beOWSldsnsomicshiSOCkz2Yfcgtxia_ianCLICLEia-uyvd12hwaIA1986NKA048a.da.ga.ba.l.kt.k.x69atcattgkody1ATOATSCybDIODIVFLYsx3HolHouxanJDFjcmITEITYITSKILigpfai_toktuktjktdOISnifnie536535539fzcSYStdo2DO4wxCluFARFASFACvythitEGRhihEGIEGGzybYBAygy-tawq3161NasNavzeuuarokeLAVqljFootqrtqybibbitABAABLudw465dsfjynyjcTibuppcficfq039bbibbsFalvgyxvcharLvbNAVuis_coOTE313nzinrf.ad.alHEW1Jorby2qwer7ertermERGGUSIBAPIMPINPIPPIT_ni_neQq1MrBOCHOCCOCTSTYrciTITSS1SSSSSMSSEon1EARAUGAUSUTOtopezdezeIUSev.MmmONYONSDUDbersunsumErifgxfgdfgbixe937ugaLCAnccYCAdthfhrkhaOutaceAutURAURT976975974973979ECRACTsx1ueluesfxbwxyzeqjxmjazzuwMMIUltPhompbThrrhb020beldpx89zvfrxuswwfznuLuvLudRPISMArezrekcjqActDBOES1ESIxzshumN?Np2JkvvOBYNumZepPHOPrenfcnfiTHAavyavinokmy_owjow1AVOmrj23!djxmkaxodrysVfrLUVLUIrjcpjhpjdpjxtjer77frfgjrCjkWayWatWarEILEINNUMtteyanyakya1ya-IYAozaRMEsabsafkiwkieUSHUS1ugz90qDocDougabufklvbGALYyywyefxdllsll-ulcitsptipturkscdeuqyuquHipHLEVANNCCjcgRS1RSO.coOlickmLEN9.0293291ildilkETAETHETMGatGamxyxxybxy6htkhtshtynwoytrythILKILVLakLadLavOADhrfODG-diawalsoots727AWKFIFdiedivLANxnfVadhytntvktoMelc17njiTAHBREbqgbqcDanbqk4t5JktkmcvzffatfabfafEJALAINTAYMOybtybkybc11-kfvkfzkfcktr.80onlSkie_bWinx4xgfxva1uglugufzkjzhjzgNY1070-boDRUDROMORMOUMOKRYAodlrjnrjhBryBrice_jfg.yzbgbbgtCEMxsxubwlsehnfhnsz12MOTKel404RRORRERRATAYGibivafvvchechieugeurCH1CHOCHUd5HhmzIMAIMIKNOhzyjet_maLLOougsourpiAPRAPE25836536336Ejqjxmxjgk246yxwyxjyxfKEV579akeekkAKSAKIspevujvuzEKAEKSyuujpwYNEycrycaBloy99RODRubBNMtuptujpjpggepacHERHEEfuzfujdjk969j3qlbePen369obernoSEPprermy737cbcqczqcjSliASIz1zfzfrazxrbHJKJunSQUwjoGRInjgFluniuRUBRUCRUTeinSH1Celcifqvjqvbevg1FrdbyqhfudiwalINTINOINCKOKKOS_88ffsfffPENPEAftd468464_rukzvkzgOGOaqzeakeavAQUdomfntfnhEACEASmagYDOYDEIQUVir_yoMakLBEad_advtortontom4zxelpgiuEvgvthUKEwyvfcyfcgKLEEL1ELMGIAGIOInd619yljXFRltwPopPooRNOkdjmydjmck.colpBATBAC09=939UESMELgdavipRMIGDOziqVILVIPODEMATORSORMladlavZIA373OMOmyrmylmycphoutlutuHIppvpKYOricny_RTSSIEUARTylrypBarBadewmGd5xfhxfo...Victhy5HIZip_so_se_suBBLRafRamTLAFhnarmur_719ska */
public class BackgroundLocationPrivacyPickerOptionsAdapter extends FbBaseAdapter {
    public ImmutableList<BackgroundLocationPrivacyPickerOption> f14851a = RegularImmutableList.a;
    public boolean f14852b = true;

    public /* synthetic */ Object getItem(int i) {
        return m15297a(i);
    }

    public final void m15299a(ImmutableList<BackgroundLocationPrivacyPickerOption> immutableList) {
        this.f14851a = immutableList;
        AdapterDetour.a(this, 1715066060);
    }

    public int getCount() {
        return this.f14851a.size();
    }

    public final BackgroundLocationPrivacyPickerOptionModel m15297a(int i) {
        return (BackgroundLocationPrivacyPickerOptionModel) this.f14851a.get(i);
    }

    public long getItemId(int i) {
        return (long) i;
    }

    public final View m15296a(int i, ViewGroup viewGroup) {
        BackgroundLocationPrivacyPickerOptionView backgroundLocationPrivacyPickerOptionView = new BackgroundLocationPrivacyPickerOptionView(viewGroup.getContext());
        backgroundLocationPrivacyPickerOptionView.f14849i.setVisibility(this.f14852b ? 0 : 8);
        return backgroundLocationPrivacyPickerOptionView;
    }

    public final void m15298a(int i, Object obj, View view, int i2, ViewGroup viewGroup) {
        BackgroundLocationPrivacyPickerOptionView backgroundLocationPrivacyPickerOptionView = (BackgroundLocationPrivacyPickerOptionView) view;
        BackgroundLocationPrivacyPickerOptionModel backgroundLocationPrivacyPickerOptionModel = (BackgroundLocationPrivacyPickerOptionModel) obj;
        backgroundLocationPrivacyPickerOptionView.f14849i.setImageResource(backgroundLocationPrivacyPickerOptionView.f14848h.a(GraphQLPrivacyOptionType.fromIconName(backgroundLocationPrivacyPickerOptionModel.m15315b().d()), Size.GLYPH));
        backgroundLocationPrivacyPickerOptionView.f14850j.setText(backgroundLocationPrivacyPickerOptionModel.m15314a());
        backgroundLocationPrivacyPickerOptionView.setContentDescription(backgroundLocationPrivacyPickerOptionModel.m15314a());
    }
}
