package com.facebook.quicklog.identifiers;

/* compiled from: work_account_password */
public class ActionId {
    public static String m83a(int i) {
        switch (i) {
            case 1:
                return "START";
            case 2:
                return "SUCCESS";
            case 3:
                return "FAIL";
            case 4:
                return "CANCEL";
            case 5:
                return "DRAW_COMPLETE";
            case 6:
                return "ON_RESUME";
            case 7:
                return "ACTIVITY_CREATED";
            case 8:
                return "CONSISTENCY_MODEL_UPDATER";
            case 9:
                return "SEND_MESSAGE";
            case 10:
                return "SUCCESS_COLD";
            case 11:
                return "SUCCESS_WARM";
            case 12:
                return "UI_IDLE";
            case 13:
                return "PHASE_ONE";
            case 14:
                return "PHASE_TWO";
            case 15:
                return "DEQUEUE";
            case 16:
                return "NETWORK_COMPLETE";
            case 17:
                return "MEMORY_CACHE_VISIT";
            case 18:
                return "DISK_CACHE_VISIT";
            case 19:
                return "CONSISTENCY_UPDATE";
            case 20:
                return "RETURN_TO_CALLER";
            case 21:
                return "PHOTO_UPLOAD_COMPLETE";
            case 22:
                return "USER_NAVIGATION_CANCELLATION";
            case 23:
                return "DB_FETCH";
            case 24:
                return "SERVER_FETCH";
            case 25:
                return "SUCCESS_CACHE";
            case 26:
                return "SUCCESS_DB";
            case 27:
                return "SUCCESS_NETWORK";
            case 28:
                return "SUCCESS_LOCAL_UNSPECIFIED";
            case 29:
                return "CACHE_UPDATED";
            case 30:
                return "DB_UPDATED";
            case 31:
                return "DATA_RECEIVED";
            case 32:
                return "DRAW_VIEW";
            case 33:
                return "DATA_EMPTY";
            case 34:
                return "CACHE_FETCH";
            case 35:
                return "PREPARE_BEGIN";
            case 36:
                return "PREPARE_END";
            case 37:
                return "ASYNC_BEGIN";
            case 38:
                return "ASYNC_END";
            case 39:
                return "REMOVE_BEGIN";
            case 40:
                return "REMOVE_END";
            case 41:
                return "BROADCAST_DONE";
            case 42:
                return "ON_RESUME_END";
            case 43:
                return "ON_ATTACH_END";
            case 44:
                return "ON_FRAGMENT_CREATE_END";
            case 45:
                return "ON_CREATE_VIEW_END";
            case 46:
                return "ON_ACTIVITY_CREATED_END";
            case 47:
                return "ON_START_END";
            case 48:
                return "QUEUED";
            case 49:
                return "IN_PROGRESS";
            case 50:
                return "INIT";
            case 51:
                return "UNKNOWN";
            case 52:
                return "RETRY_AFTER_FAILURE";
            case 53:
                return "RETRY_AFTER_RECONNECT";
            case 54:
                return "QUEUEING_BEGIN";
            case 55:
                return "QUEUEING_SUCCESS";
            case 56:
                return "QUEUEING_FAIL";
            case 57:
                return "MESSAGE_UPDATE_START";
            case 58:
                return "MESSAGE_UPDATE_END";
            case 59:
                return "PHOTO_CAPTURED";
            case 60:
                return "MEDIA_PREVIEW_VISIBLE";
            case 61:
                return "COUNTER";
            case 62:
                return "INTERACTION_LOAD_TIMELINE_HEADER";
            case 63:
                return "INTERACTION_LOAD_EVENT_PERMALINK";
            case 64:
                return "INTERACTION_LOAD_GROUPS_FEED";
            case 65:
                return "INTERACTION_LOAD_PAGE_HEADER";
            case 66:
                return "INTERACTION_LOAD_PAGE_HEADER_ADMIN";
            case 67:
                return "INTERACTION_LOAD_PERMALINK";
            case 68:
                return "INTERACTION_OPEN_COMPOSER";
            case 69:
                return "INTERACTION_OPEN_MEDIA_PICKER";
            case 70:
                return "INTERACTION_OPEN_PHOTO_GALLERY";
            case 71:
                return "INTERACTION_OPEN_CHECK_IN";
            case 72:
                return "INTERACTION_LOAD_WEB_VIEW";
            case 73:
                return "INTENT_MAPPED";
            case 74:
                return "ACTIVITY_LAUNCHED";
            case 75:
                return "ACTIVITY_PAUSED";
            case 76:
                return "ACTIVITY_STARTED";
            case 77:
                return "ACTIVITY_RESUMED";
            case 78:
                return "FRAGMENT_CREATED";
            case 79:
                return "FRAGMENT_RESUMED";
            case 80:
                return "ACTIVITY_ON_CREATE";
            case 81:
                return "INTENT_MAPPING_BEGIN";
            case 82:
                return "FRAGMENT_ON_CREATE";
            case 83:
                return "FRAGMENT_NEW_INSTANCE";
            case 84:
                return "MARKER_SWAPPED";
            case 85:
                return "FRAGMENT_INSTANCE_CREATED";
            case 86:
                return "PREV_ACTIVITY_PAUSED";
            case 87:
                return "ERROR";
            case 88:
                return "METHOD_INVOKE";
            case 89:
                return "FINALLY";
            case 90:
                return "PHOTO_DOWNLOAD_COMPLETE";
            case 91:
                return "MINIPREVIEW_COMPLETE";
            case 92:
                return "SEARCH_TYPEAHEAD";
            case 93:
                return "ANIMATION_END";
            case 94:
                return "UDP_REQUEST_SEND";
            case 95:
                return "MAIN_COMPLETE";
            case 96:
                return "INTERRUPTED";
            case 97:
                return "NETWORK_FAILED";
            case 98:
                return "NETWORK_RESPONSE";
            case 99:
                return "EDGE_PROCESSING_BEGIN";
            case 100:
                return "NEWSFEED_PROCESS_RESPONSE";
            case 101:
                return "ON_VIEW_CREATED_END";
            case 102:
                return "DATA_LOAD_START";
            case 103:
                return "LEGACY_MARKER";
            case 104:
                return "ACTION_BAR_COMPLETE";
            case 105:
                return "ABORTED";
            case 106:
                return "QUERY_READY";
            case 107:
                return "RTMP_PACKET_RECEIVED";
            case 108:
                return "REQUESTED_PLAYING";
            case 109:
                return "RTMP_CONNECTION_REQUESTED";
            case 110:
                return "RTMP_CONNECTION_RELEASE";
            case 111:
                return "NEW_START_FOUND";
            case 112:
                return "MISSED_EVENT";
            case 113:
                return "TIMEOUT";
            case 114:
                return "CONTROLLER_INITIATED";
            case 115:
                return "RTMP_STREAM_PREPARED";
            case 116:
                return "VIDEO_PLAYING";
            case 117:
                return "RTMP_CONNECTION_CONNECTED";
            case 118:
                return "RTMP_CONNECTION_FAILED";
            case 119:
                return "RTMP_CONNECTION_INTERCEPTED";
            case 120:
                return "VIDEO_SET_RENDERER_CONTEXT";
            case 121:
                return "HEADER_DATA_LOADED";
            case 122:
                return "CARD_DATA_LOADED";
            case 123:
                return "VIEW_WILL_APPEAR_BEGIN";
            case 124:
                return "VIEW_DID_LOAD_BEGIN";
            case 125:
                return "COMPONENTS_DATA_SOURCE_WILL_BEGIN_UPDATES";
            case 126:
                return "COMPONENTS_DATA_SOURCE_DID_END_UPDATES";
            case 127:
                return "LOAD_VIEW_BEGIN";
            case 128:
                return "RTMP_FIRST_KEY_FRAME_RECEIVED";
            case 129:
                return "MESSENGER_QUEUE_CREATION";
            case 130:
                return "APP_DID_FINISH_LAUNCHING";
            case 131:
                return "APP_DID_BECOME_ACTIVE";
            case 132:
                return "APP_WILL_ENTER_FOREGROUND";
            case 133:
                return "APP_DID_ENTER_BACKGROUND";
            case 134:
                return "APP_MAIN";
            case 135:
                return "MQTT_CONNECTING";
            case 136:
                return "MQTT_CONNECTED";
            case 137:
                return "MQTT_DISCONNECTED";
            case 138:
                return "MESSENGER_DELTA_REQUEST";
            case 139:
                return "APP_FIRST_VIEW_CONTROLLER";
            case 140:
                return "MESSENGER_THREAD_LIST_LOADED";
            case 141:
                return "MESSENGER_THREAD_LIST_DISPLAYED";
            case 142:
                return "PREV_ACTIVITY_PAUSE";
            case 143:
                return "ACTIVITY_RESUME";
            case 144:
                return "ACTIVITY_START";
            case 145:
                return "BEGIN_START_ACTIVITY";
            case 146:
                return "END_START_ACTIVITY";
            case 147:
                return "FILE_SYSTEM_FAIL";
            case 148:
                return "FORMAT_ERROR";
            case 149:
                return "PRIVACY_VIOLATION";
            case 150:
                return "NETWORK_RESPONSE_INITIAL_SCAN";
            case 151:
                return "POPULATE_CONSISTENCY_MEMORY_CACHE";
            case 152:
                return "APPLY_OPTIMISTICS";
            case 153:
                return "APPLY_FINISHED_LIST";
            case 154:
                return "APPLY_FINISHED_LIST_AGAIN";
            case 155:
                return "FUTURE_LISTENERS_COMPLETE";
            case 156:
                return "SERVICE_ON_START_COMMAND";
            case 157:
                return "WAIT_FOR_BLOCKERS";
            case 158:
                return "NOTIFY_SUBSCRIBERS";
            case 159:
                return "FAIL_FILE_TOO_LARGE";
            case 160:
                return "OFFLINE";
            case 161:
                return "ASNYC_FAILED";
            case 162:
                return "ASYNC_FAIL";
            case 163:
                return "ON_ATTACH_FRAGMENT";
            case 164:
                return "VIEW_DID_APPEAR_BEGIN";
            case 165:
                return "DISPLAYED";
            case 166:
                return "DISPLAYED_ON_SCREEN";
            default:
                return "UNDEFINED_QPL_ACTION";
        }
    }
}
