package com.facebook.auth.userscope;

import com.facebook.inject.AutoGeneratedBinder;

@AutoGeneratedBinder
/* compiled from: use_count */
public final class AutoGeneratedBindingsForUserScopeModule {
}
