package com.facebook.backgroundworklog;

import com.facebook.inject.AutoGeneratedBinder;

@AutoGeneratedBinder
/* compiled from: selected_ad_account_has_payment_method */
public final class AutoGeneratedBindingsForBackgroundWorkLogModule {
}
