package com.facebook.config.application;

import com.facebook.inject.AutoGeneratedBinder;

@AutoGeneratedBinder
/* compiled from: use_hw */
public final class AutoGeneratedBindingsForFbAppTypeModule {
}
