package com.facebook.friendlist.constants;

/* compiled from: fetch_status */
public enum FriendListSource {
    FRIEND_LIST_ALL_TAB,
    FRIEND_LIST_MUTUAL_TAB,
    FRIEND_LIST_RECENT_TAB,
    FRIEND_LIST_SUGGESTIONS_TAB,
    FRIEND_LIST_WITH_NEW_POSTS_TAB,
    FRIENDS_TAB_SEE_ALL_FRIENDS,
    FRIENDS_TAB_FRIEND_OVERFLOW_MENU,
    FRIENDS_TAB_SPROUT_LAUNCHER,
    TIMELINE_ABOUT_FRIENDS_APP,
    TIMELINE_ABOUT_FRIENDS_APP_MUTUAL_FRIENDS_LINK,
    TIMELINE_CONTEXT_ITEM,
    TIMELINE_FRIENDS_NAVTILE,
    TIMELINE_FRIENDS_PROTILE,
    TIMELINE_SURFING_RECOMMENDATIONS,
    BOOKMARK,
    FEED_PYMK
}
