package com.facebook.datasensitivity.analytics;

/* compiled from: _size */
enum DsmAnalyticsEventLogger$EventType {
    SETTINGS_DSM_ENABLED,
    SETTINGS_DSM_DISABLED,
    CONFIRMATION_DIALOG_SHOWN,
    CONFIRMATION_DIALOG_OK_CLICKED,
    CONFIRMATION_DIALOG_TO_SETTING_CLICKED,
    SETTINGS_DSM_AUTO_ENABLED,
    SETTINGS_DSM_AUTO_DISABLED,
    PROMOTION_NOT_NOW_CLICKED,
    PROMOTION_TURN_ON_CLICKED
}
