package com.facebook.phonenumbers;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/* compiled from: egl_mtrack */
public class CountryCodeToRegionCodeMap {
    public static Map<Integer, List<String>> sCountryCodeToRegionCodeMap;
    public static Map<String, Integer> sRegionCodeToCountryCodeMap;

    public static void maybeInitializeMaps() {
        if (sCountryCodeToRegionCodeMap == null || sRegionCodeToCountryCodeMap == null) {
            Map hashMap = new HashMap(286);
            Map hashMap2 = new HashMap(326);
            ArrayList arrayList = new ArrayList(25);
            arrayList.add("US");
            hashMap2.put("US", Integer.valueOf(1));
            arrayList.add("AG");
            hashMap2.put("AG", Integer.valueOf(1));
            arrayList.add("AI");
            hashMap2.put("AI", Integer.valueOf(1));
            arrayList.add("AS");
            hashMap2.put("AS", Integer.valueOf(1));
            arrayList.add("BB");
            hashMap2.put("BB", Integer.valueOf(1));
            arrayList.add("BM");
            hashMap2.put("BM", Integer.valueOf(1));
            arrayList.add("BS");
            hashMap2.put("BS", Integer.valueOf(1));
            arrayList.add("CA");
            hashMap2.put("CA", Integer.valueOf(1));
            arrayList.add("DM");
            hashMap2.put("DM", Integer.valueOf(1));
            arrayList.add("DO");
            hashMap2.put("DO", Integer.valueOf(1));
            arrayList.add("GD");
            hashMap2.put("GD", Integer.valueOf(1));
            arrayList.add("GU");
            hashMap2.put("GU", Integer.valueOf(1));
            arrayList.add("JM");
            hashMap2.put("JM", Integer.valueOf(1));
            arrayList.add("KN");
            hashMap2.put("KN", Integer.valueOf(1));
            arrayList.add("KY");
            hashMap2.put("KY", Integer.valueOf(1));
            arrayList.add("LC");
            hashMap2.put("LC", Integer.valueOf(1));
            arrayList.add("MP");
            hashMap2.put("MP", Integer.valueOf(1));
            arrayList.add("MS");
            hashMap2.put("MS", Integer.valueOf(1));
            arrayList.add("PR");
            hashMap2.put("PR", Integer.valueOf(1));
            arrayList.add("SX");
            hashMap2.put("SX", Integer.valueOf(1));
            arrayList.add("TC");
            hashMap2.put("TC", Integer.valueOf(1));
            arrayList.add("TT");
            hashMap2.put("TT", Integer.valueOf(1));
            arrayList.add("VC");
            hashMap2.put("VC", Integer.valueOf(1));
            arrayList.add("VG");
            hashMap2.put("VG", Integer.valueOf(1));
            arrayList.add("VI");
            hashMap2.put("VI", Integer.valueOf(1));
            hashMap.put(Integer.valueOf(1), arrayList);
            arrayList = new ArrayList(2);
            arrayList.add("RU");
            hashMap2.put("RU", Integer.valueOf(7));
            arrayList.add("KZ");
            hashMap2.put("KZ", Integer.valueOf(7));
            hashMap.put(Integer.valueOf(7), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("EG");
            hashMap2.put("EG", Integer.valueOf(20));
            hashMap.put(Integer.valueOf(20), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("ZA");
            hashMap2.put("ZA", Integer.valueOf(27));
            hashMap.put(Integer.valueOf(27), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("GR");
            hashMap2.put("GR", Integer.valueOf(30));
            hashMap.put(Integer.valueOf(30), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("NL");
            hashMap2.put("NL", Integer.valueOf(31));
            hashMap.put(Integer.valueOf(31), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("BE");
            hashMap2.put("BE", Integer.valueOf(32));
            hashMap.put(Integer.valueOf(32), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("FR");
            hashMap2.put("FR", Integer.valueOf(33));
            hashMap.put(Integer.valueOf(33), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("ES");
            hashMap2.put("ES", Integer.valueOf(34));
            hashMap.put(Integer.valueOf(34), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("HU");
            hashMap2.put("HU", Integer.valueOf(36));
            hashMap.put(Integer.valueOf(36), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("IT");
            hashMap2.put("IT", Integer.valueOf(39));
            hashMap.put(Integer.valueOf(39), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("RO");
            hashMap2.put("RO", Integer.valueOf(40));
            hashMap.put(Integer.valueOf(40), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("CH");
            hashMap2.put("CH", Integer.valueOf(41));
            hashMap.put(Integer.valueOf(41), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("AT");
            hashMap2.put("AT", Integer.valueOf(43));
            hashMap.put(Integer.valueOf(43), arrayList);
            arrayList = new ArrayList(4);
            arrayList.add("GB");
            hashMap2.put("GB", Integer.valueOf(44));
            arrayList.add("GG");
            hashMap2.put("GG", Integer.valueOf(44));
            arrayList.add("IM");
            hashMap2.put("IM", Integer.valueOf(44));
            arrayList.add("JE");
            hashMap2.put("JE", Integer.valueOf(44));
            hashMap.put(Integer.valueOf(44), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("DK");
            hashMap2.put("DK", Integer.valueOf(45));
            hashMap.put(Integer.valueOf(45), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("SE");
            hashMap2.put("SE", Integer.valueOf(46));
            hashMap.put(Integer.valueOf(46), arrayList);
            arrayList = new ArrayList(2);
            arrayList.add("NO");
            hashMap2.put("NO", Integer.valueOf(47));
            arrayList.add("SJ");
            hashMap2.put("SJ", Integer.valueOf(47));
            hashMap.put(Integer.valueOf(47), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("PL");
            hashMap2.put("PL", Integer.valueOf(48));
            hashMap.put(Integer.valueOf(48), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("DE");
            hashMap2.put("DE", Integer.valueOf(49));
            hashMap.put(Integer.valueOf(49), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("PE");
            hashMap2.put("PE", Integer.valueOf(51));
            hashMap.put(Integer.valueOf(51), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("MX");
            hashMap2.put("MX", Integer.valueOf(52));
            hashMap.put(Integer.valueOf(52), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("CU");
            hashMap2.put("CU", Integer.valueOf(53));
            hashMap.put(Integer.valueOf(53), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("AR");
            hashMap2.put("AR", Integer.valueOf(54));
            hashMap.put(Integer.valueOf(54), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("BR");
            hashMap2.put("BR", Integer.valueOf(55));
            hashMap.put(Integer.valueOf(55), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("CL");
            hashMap2.put("CL", Integer.valueOf(56));
            hashMap.put(Integer.valueOf(56), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("CO");
            hashMap2.put("CO", Integer.valueOf(57));
            hashMap.put(Integer.valueOf(57), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("VE");
            hashMap2.put("VE", Integer.valueOf(58));
            hashMap.put(Integer.valueOf(58), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("MY");
            hashMap2.put("MY", Integer.valueOf(60));
            hashMap.put(Integer.valueOf(60), arrayList);
            arrayList = new ArrayList(3);
            arrayList.add("AU");
            hashMap2.put("AU", Integer.valueOf(61));
            arrayList.add("CC");
            hashMap2.put("CC", Integer.valueOf(61));
            arrayList.add("CX");
            hashMap2.put("CX", Integer.valueOf(61));
            hashMap.put(Integer.valueOf(61), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("ID");
            hashMap2.put("ID", Integer.valueOf(62));
            hashMap.put(Integer.valueOf(62), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("PH");
            hashMap2.put("PH", Integer.valueOf(63));
            hashMap.put(Integer.valueOf(63), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("NZ");
            hashMap2.put("NZ", Integer.valueOf(64));
            hashMap.put(Integer.valueOf(64), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("SG");
            hashMap2.put("SG", Integer.valueOf(65));
            hashMap.put(Integer.valueOf(65), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("TH");
            hashMap2.put("TH", Integer.valueOf(66));
            hashMap.put(Integer.valueOf(66), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("JP");
            hashMap2.put("JP", Integer.valueOf(81));
            hashMap.put(Integer.valueOf(81), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("KR");
            hashMap2.put("KR", Integer.valueOf(82));
            hashMap.put(Integer.valueOf(82), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("VN");
            hashMap2.put("VN", Integer.valueOf(84));
            hashMap.put(Integer.valueOf(84), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("CN");
            hashMap2.put("CN", Integer.valueOf(86));
            hashMap.put(Integer.valueOf(86), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("TR");
            hashMap2.put("TR", Integer.valueOf(90));
            hashMap.put(Integer.valueOf(90), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("IN");
            hashMap2.put("IN", Integer.valueOf(91));
            hashMap.put(Integer.valueOf(91), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("PK");
            hashMap2.put("PK", Integer.valueOf(92));
            hashMap.put(Integer.valueOf(92), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("AF");
            hashMap2.put("AF", Integer.valueOf(93));
            hashMap.put(Integer.valueOf(93), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("LK");
            hashMap2.put("LK", Integer.valueOf(94));
            hashMap.put(Integer.valueOf(94), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("MM");
            hashMap2.put("MM", Integer.valueOf(95));
            hashMap.put(Integer.valueOf(95), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("IR");
            hashMap2.put("IR", Integer.valueOf(98));
            hashMap.put(Integer.valueOf(98), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("SS");
            hashMap2.put("SS", Integer.valueOf(211));
            hashMap.put(Integer.valueOf(211), arrayList);
            arrayList = new ArrayList(2);
            arrayList.add("MA");
            hashMap2.put("MA", Integer.valueOf(212));
            arrayList.add("EH");
            hashMap2.put("EH", Integer.valueOf(212));
            hashMap.put(Integer.valueOf(212), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("DZ");
            hashMap2.put("DZ", Integer.valueOf(213));
            hashMap.put(Integer.valueOf(213), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("TN");
            hashMap2.put("TN", Integer.valueOf(216));
            hashMap.put(Integer.valueOf(216), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("LY");
            hashMap2.put("LY", Integer.valueOf(218));
            hashMap.put(Integer.valueOf(218), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("GM");
            hashMap2.put("GM", Integer.valueOf(220));
            hashMap.put(Integer.valueOf(220), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("SN");
            hashMap2.put("SN", Integer.valueOf(221));
            hashMap.put(Integer.valueOf(221), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("MR");
            hashMap2.put("MR", Integer.valueOf(222));
            hashMap.put(Integer.valueOf(222), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("ML");
            hashMap2.put("ML", Integer.valueOf(223));
            hashMap.put(Integer.valueOf(223), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("GN");
            hashMap2.put("GN", Integer.valueOf(224));
            hashMap.put(Integer.valueOf(224), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("CI");
            hashMap2.put("CI", Integer.valueOf(225));
            hashMap.put(Integer.valueOf(225), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("BF");
            hashMap2.put("BF", Integer.valueOf(226));
            hashMap.put(Integer.valueOf(226), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("NE");
            hashMap2.put("NE", Integer.valueOf(227));
            hashMap.put(Integer.valueOf(227), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("TG");
            hashMap2.put("TG", Integer.valueOf(228));
            hashMap.put(Integer.valueOf(228), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("BJ");
            hashMap2.put("BJ", Integer.valueOf(229));
            hashMap.put(Integer.valueOf(229), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("MU");
            hashMap2.put("MU", Integer.valueOf(230));
            hashMap.put(Integer.valueOf(230), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("LR");
            hashMap2.put("LR", Integer.valueOf(231));
            hashMap.put(Integer.valueOf(231), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("SL");
            hashMap2.put("SL", Integer.valueOf(232));
            hashMap.put(Integer.valueOf(232), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("GH");
            hashMap2.put("GH", Integer.valueOf(233));
            hashMap.put(Integer.valueOf(233), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("NG");
            hashMap2.put("NG", Integer.valueOf(234));
            hashMap.put(Integer.valueOf(234), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("TD");
            hashMap2.put("TD", Integer.valueOf(235));
            hashMap.put(Integer.valueOf(235), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("CF");
            hashMap2.put("CF", Integer.valueOf(236));
            hashMap.put(Integer.valueOf(236), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("CM");
            hashMap2.put("CM", Integer.valueOf(237));
            hashMap.put(Integer.valueOf(237), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("CV");
            hashMap2.put("CV", Integer.valueOf(238));
            hashMap.put(Integer.valueOf(238), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("ST");
            hashMap2.put("ST", Integer.valueOf(239));
            hashMap.put(Integer.valueOf(239), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("GQ");
            hashMap2.put("GQ", Integer.valueOf(240));
            hashMap.put(Integer.valueOf(240), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("GA");
            hashMap2.put("GA", Integer.valueOf(241));
            hashMap.put(Integer.valueOf(241), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("CG");
            hashMap2.put("CG", Integer.valueOf(242));
            hashMap.put(Integer.valueOf(242), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("CD");
            hashMap2.put("CD", Integer.valueOf(243));
            hashMap.put(Integer.valueOf(243), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("AO");
            hashMap2.put("AO", Integer.valueOf(244));
            hashMap.put(Integer.valueOf(244), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("GW");
            hashMap2.put("GW", Integer.valueOf(245));
            hashMap.put(Integer.valueOf(245), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("IO");
            hashMap2.put("IO", Integer.valueOf(246));
            hashMap.put(Integer.valueOf(246), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("AC");
            hashMap2.put("AC", Integer.valueOf(247));
            hashMap.put(Integer.valueOf(247), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("SC");
            hashMap2.put("SC", Integer.valueOf(248));
            hashMap.put(Integer.valueOf(248), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("SD");
            hashMap2.put("SD", Integer.valueOf(249));
            hashMap.put(Integer.valueOf(249), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("RW");
            hashMap2.put("RW", Integer.valueOf(250));
            hashMap.put(Integer.valueOf(250), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("ET");
            hashMap2.put("ET", Integer.valueOf(251));
            hashMap.put(Integer.valueOf(251), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("SO");
            hashMap2.put("SO", Integer.valueOf(252));
            hashMap.put(Integer.valueOf(252), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("DJ");
            hashMap2.put("DJ", Integer.valueOf(253));
            hashMap.put(Integer.valueOf(253), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("KE");
            hashMap2.put("KE", Integer.valueOf(254));
            hashMap.put(Integer.valueOf(254), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("TZ");
            hashMap2.put("TZ", Integer.valueOf(255));
            hashMap.put(Integer.valueOf(255), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("UG");
            hashMap2.put("UG", Integer.valueOf(256));
            hashMap.put(Integer.valueOf(256), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("BI");
            hashMap2.put("BI", Integer.valueOf(257));
            hashMap.put(Integer.valueOf(257), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("MZ");
            hashMap2.put("MZ", Integer.valueOf(258));
            hashMap.put(Integer.valueOf(258), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("ZM");
            hashMap2.put("ZM", Integer.valueOf(260));
            hashMap.put(Integer.valueOf(260), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("MG");
            hashMap2.put("MG", Integer.valueOf(261));
            hashMap.put(Integer.valueOf(261), arrayList);
            arrayList = new ArrayList(2);
            arrayList.add("RE");
            hashMap2.put("RE", Integer.valueOf(262));
            arrayList.add("YT");
            hashMap2.put("YT", Integer.valueOf(262));
            hashMap.put(Integer.valueOf(262), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("ZW");
            hashMap2.put("ZW", Integer.valueOf(263));
            hashMap.put(Integer.valueOf(263), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("NA");
            hashMap2.put("NA", Integer.valueOf(264));
            hashMap.put(Integer.valueOf(264), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("MW");
            hashMap2.put("MW", Integer.valueOf(265));
            hashMap.put(Integer.valueOf(265), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("LS");
            hashMap2.put("LS", Integer.valueOf(266));
            hashMap.put(Integer.valueOf(266), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("BW");
            hashMap2.put("BW", Integer.valueOf(267));
            hashMap.put(Integer.valueOf(267), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("SZ");
            hashMap2.put("SZ", Integer.valueOf(268));
            hashMap.put(Integer.valueOf(268), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("KM");
            hashMap2.put("KM", Integer.valueOf(269));
            hashMap.put(Integer.valueOf(269), arrayList);
            arrayList = new ArrayList(2);
            arrayList.add("SH");
            hashMap2.put("SH", Integer.valueOf(290));
            arrayList.add("TA");
            hashMap2.put("TA", Integer.valueOf(290));
            hashMap.put(Integer.valueOf(290), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("ER");
            hashMap2.put("ER", Integer.valueOf(291));
            hashMap.put(Integer.valueOf(291), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("AW");
            hashMap2.put("AW", Integer.valueOf(297));
            hashMap.put(Integer.valueOf(297), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("FO");
            hashMap2.put("FO", Integer.valueOf(298));
            hashMap.put(Integer.valueOf(298), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("GL");
            hashMap2.put("GL", Integer.valueOf(299));
            hashMap.put(Integer.valueOf(299), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("GI");
            hashMap2.put("GI", Integer.valueOf(350));
            hashMap.put(Integer.valueOf(350), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("PT");
            hashMap2.put("PT", Integer.valueOf(351));
            hashMap.put(Integer.valueOf(351), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("LU");
            hashMap2.put("LU", Integer.valueOf(352));
            hashMap.put(Integer.valueOf(352), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("IE");
            hashMap2.put("IE", Integer.valueOf(353));
            hashMap.put(Integer.valueOf(353), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("IS");
            hashMap2.put("IS", Integer.valueOf(354));
            hashMap.put(Integer.valueOf(354), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("AL");
            hashMap2.put("AL", Integer.valueOf(355));
            hashMap.put(Integer.valueOf(355), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("MT");
            hashMap2.put("MT", Integer.valueOf(356));
            hashMap.put(Integer.valueOf(356), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("CY");
            hashMap2.put("CY", Integer.valueOf(357));
            hashMap.put(Integer.valueOf(357), arrayList);
            arrayList = new ArrayList(2);
            arrayList.add("FI");
            hashMap2.put("FI", Integer.valueOf(358));
            arrayList.add("AX");
            hashMap2.put("AX", Integer.valueOf(358));
            hashMap.put(Integer.valueOf(358), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("BG");
            hashMap2.put("BG", Integer.valueOf(359));
            hashMap.put(Integer.valueOf(359), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("LT");
            hashMap2.put("LT", Integer.valueOf(370));
            hashMap.put(Integer.valueOf(370), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("LV");
            hashMap2.put("LV", Integer.valueOf(371));
            hashMap.put(Integer.valueOf(371), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("EE");
            hashMap2.put("EE", Integer.valueOf(372));
            hashMap.put(Integer.valueOf(372), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("MD");
            hashMap2.put("MD", Integer.valueOf(373));
            hashMap.put(Integer.valueOf(373), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("AM");
            hashMap2.put("AM", Integer.valueOf(374));
            hashMap.put(Integer.valueOf(374), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("BY");
            hashMap2.put("BY", Integer.valueOf(375));
            hashMap.put(Integer.valueOf(375), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("AD");
            hashMap2.put("AD", Integer.valueOf(376));
            hashMap.put(Integer.valueOf(376), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("MC");
            hashMap2.put("MC", Integer.valueOf(377));
            hashMap.put(Integer.valueOf(377), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("SM");
            hashMap2.put("SM", Integer.valueOf(378));
            hashMap.put(Integer.valueOf(378), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("VA");
            hashMap2.put("VA", Integer.valueOf(379));
            hashMap.put(Integer.valueOf(379), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("UA");
            hashMap2.put("UA", Integer.valueOf(380));
            hashMap.put(Integer.valueOf(380), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("RS");
            hashMap2.put("RS", Integer.valueOf(381));
            hashMap.put(Integer.valueOf(381), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("ME");
            hashMap2.put("ME", Integer.valueOf(382));
            hashMap.put(Integer.valueOf(382), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("HR");
            hashMap2.put("HR", Integer.valueOf(385));
            hashMap.put(Integer.valueOf(385), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("SI");
            hashMap2.put("SI", Integer.valueOf(386));
            hashMap.put(Integer.valueOf(386), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("BA");
            hashMap2.put("BA", Integer.valueOf(387));
            hashMap.put(Integer.valueOf(387), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("MK");
            hashMap2.put("MK", Integer.valueOf(389));
            hashMap.put(Integer.valueOf(389), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("CZ");
            hashMap2.put("CZ", Integer.valueOf(420));
            hashMap.put(Integer.valueOf(420), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("SK");
            hashMap2.put("SK", Integer.valueOf(421));
            hashMap.put(Integer.valueOf(421), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("LI");
            hashMap2.put("LI", Integer.valueOf(423));
            hashMap.put(Integer.valueOf(423), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("FK");
            hashMap2.put("FK", Integer.valueOf(500));
            hashMap.put(Integer.valueOf(500), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("BZ");
            hashMap2.put("BZ", Integer.valueOf(501));
            hashMap.put(Integer.valueOf(501), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("GT");
            hashMap2.put("GT", Integer.valueOf(502));
            hashMap.put(Integer.valueOf(502), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("SV");
            hashMap2.put("SV", Integer.valueOf(503));
            hashMap.put(Integer.valueOf(503), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("HN");
            hashMap2.put("HN", Integer.valueOf(504));
            hashMap.put(Integer.valueOf(504), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("NI");
            hashMap2.put("NI", Integer.valueOf(505));
            hashMap.put(Integer.valueOf(505), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("CR");
            hashMap2.put("CR", Integer.valueOf(506));
            hashMap.put(Integer.valueOf(506), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("PA");
            hashMap2.put("PA", Integer.valueOf(507));
            hashMap.put(Integer.valueOf(507), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("PM");
            hashMap2.put("PM", Integer.valueOf(508));
            hashMap.put(Integer.valueOf(508), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("HT");
            hashMap2.put("HT", Integer.valueOf(509));
            hashMap.put(Integer.valueOf(509), arrayList);
            arrayList = new ArrayList(3);
            arrayList.add("GP");
            hashMap2.put("GP", Integer.valueOf(590));
            arrayList.add("BL");
            hashMap2.put("BL", Integer.valueOf(590));
            arrayList.add("MF");
            hashMap2.put("MF", Integer.valueOf(590));
            hashMap.put(Integer.valueOf(590), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("BO");
            hashMap2.put("BO", Integer.valueOf(591));
            hashMap.put(Integer.valueOf(591), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("GY");
            hashMap2.put("GY", Integer.valueOf(592));
            hashMap.put(Integer.valueOf(592), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("EC");
            hashMap2.put("EC", Integer.valueOf(593));
            hashMap.put(Integer.valueOf(593), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("GF");
            hashMap2.put("GF", Integer.valueOf(594));
            hashMap.put(Integer.valueOf(594), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("PY");
            hashMap2.put("PY", Integer.valueOf(595));
            hashMap.put(Integer.valueOf(595), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("MQ");
            hashMap2.put("MQ", Integer.valueOf(596));
            hashMap.put(Integer.valueOf(596), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("SR");
            hashMap2.put("SR", Integer.valueOf(597));
            hashMap.put(Integer.valueOf(597), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("UY");
            hashMap2.put("UY", Integer.valueOf(598));
            hashMap.put(Integer.valueOf(598), arrayList);
            arrayList = new ArrayList(2);
            arrayList.add("CW");
            hashMap2.put("CW", Integer.valueOf(599));
            arrayList.add("BQ");
            hashMap2.put("BQ", Integer.valueOf(599));
            hashMap.put(Integer.valueOf(599), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("TL");
            hashMap2.put("TL", Integer.valueOf(670));
            hashMap.put(Integer.valueOf(670), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("NF");
            hashMap2.put("NF", Integer.valueOf(672));
            hashMap.put(Integer.valueOf(672), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("BN");
            hashMap2.put("BN", Integer.valueOf(673));
            hashMap.put(Integer.valueOf(673), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("NR");
            hashMap2.put("NR", Integer.valueOf(674));
            hashMap.put(Integer.valueOf(674), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("PG");
            hashMap2.put("PG", Integer.valueOf(675));
            hashMap.put(Integer.valueOf(675), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("TO");
            hashMap2.put("TO", Integer.valueOf(676));
            hashMap.put(Integer.valueOf(676), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("SB");
            hashMap2.put("SB", Integer.valueOf(677));
            hashMap.put(Integer.valueOf(677), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("VU");
            hashMap2.put("VU", Integer.valueOf(678));
            hashMap.put(Integer.valueOf(678), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("FJ");
            hashMap2.put("FJ", Integer.valueOf(679));
            hashMap.put(Integer.valueOf(679), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("PW");
            hashMap2.put("PW", Integer.valueOf(680));
            hashMap.put(Integer.valueOf(680), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("WF");
            hashMap2.put("WF", Integer.valueOf(681));
            hashMap.put(Integer.valueOf(681), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("CK");
            hashMap2.put("CK", Integer.valueOf(682));
            hashMap.put(Integer.valueOf(682), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("NU");
            hashMap2.put("NU", Integer.valueOf(683));
            hashMap.put(Integer.valueOf(683), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("WS");
            hashMap2.put("WS", Integer.valueOf(685));
            hashMap.put(Integer.valueOf(685), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("KI");
            hashMap2.put("KI", Integer.valueOf(686));
            hashMap.put(Integer.valueOf(686), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("NC");
            hashMap2.put("NC", Integer.valueOf(687));
            hashMap.put(Integer.valueOf(687), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("TV");
            hashMap2.put("TV", Integer.valueOf(688));
            hashMap.put(Integer.valueOf(688), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("PF");
            hashMap2.put("PF", Integer.valueOf(689));
            hashMap.put(Integer.valueOf(689), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("TK");
            hashMap2.put("TK", Integer.valueOf(690));
            hashMap.put(Integer.valueOf(690), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("FM");
            hashMap2.put("FM", Integer.valueOf(691));
            hashMap.put(Integer.valueOf(691), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("MH");
            hashMap2.put("MH", Integer.valueOf(692));
            hashMap.put(Integer.valueOf(692), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("001");
            hashMap.put(Integer.valueOf(800), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("001");
            hashMap.put(Integer.valueOf(808), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("KP");
            hashMap2.put("KP", Integer.valueOf(850));
            hashMap.put(Integer.valueOf(850), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("HK");
            hashMap2.put("HK", Integer.valueOf(852));
            hashMap.put(Integer.valueOf(852), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("MO");
            hashMap2.put("MO", Integer.valueOf(853));
            hashMap.put(Integer.valueOf(853), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("KH");
            hashMap2.put("KH", Integer.valueOf(855));
            hashMap.put(Integer.valueOf(855), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("LA");
            hashMap2.put("LA", Integer.valueOf(856));
            hashMap.put(Integer.valueOf(856), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("001");
            hashMap.put(Integer.valueOf(870), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("001");
            hashMap.put(Integer.valueOf(878), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("BD");
            hashMap2.put("BD", Integer.valueOf(880));
            hashMap.put(Integer.valueOf(880), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("001");
            hashMap.put(Integer.valueOf(881), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("001");
            hashMap.put(Integer.valueOf(882), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("001");
            hashMap.put(Integer.valueOf(883), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("TW");
            hashMap2.put("TW", Integer.valueOf(886));
            hashMap.put(Integer.valueOf(886), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("001");
            hashMap.put(Integer.valueOf(888), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("MV");
            hashMap2.put("MV", Integer.valueOf(960));
            hashMap.put(Integer.valueOf(960), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("LB");
            hashMap2.put("LB", Integer.valueOf(961));
            hashMap.put(Integer.valueOf(961), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("JO");
            hashMap2.put("JO", Integer.valueOf(962));
            hashMap.put(Integer.valueOf(962), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("SY");
            hashMap2.put("SY", Integer.valueOf(963));
            hashMap.put(Integer.valueOf(963), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("IQ");
            hashMap2.put("IQ", Integer.valueOf(964));
            hashMap.put(Integer.valueOf(964), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("KW");
            hashMap2.put("KW", Integer.valueOf(965));
            hashMap.put(Integer.valueOf(965), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("SA");
            hashMap2.put("SA", Integer.valueOf(966));
            hashMap.put(Integer.valueOf(966), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("YE");
            hashMap2.put("YE", Integer.valueOf(967));
            hashMap.put(Integer.valueOf(967), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("OM");
            hashMap2.put("OM", Integer.valueOf(968));
            hashMap.put(Integer.valueOf(968), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("PS");
            hashMap2.put("PS", Integer.valueOf(970));
            hashMap.put(Integer.valueOf(970), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("AE");
            hashMap2.put("AE", Integer.valueOf(971));
            hashMap.put(Integer.valueOf(971), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("IL");
            hashMap2.put("IL", Integer.valueOf(972));
            hashMap.put(Integer.valueOf(972), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("BH");
            hashMap2.put("BH", Integer.valueOf(973));
            hashMap.put(Integer.valueOf(973), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("QA");
            hashMap2.put("QA", Integer.valueOf(974));
            hashMap.put(Integer.valueOf(974), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("BT");
            hashMap2.put("BT", Integer.valueOf(975));
            hashMap.put(Integer.valueOf(975), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("MN");
            hashMap2.put("MN", Integer.valueOf(976));
            hashMap.put(Integer.valueOf(976), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("NP");
            hashMap2.put("NP", Integer.valueOf(977));
            hashMap.put(Integer.valueOf(977), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("001");
            hashMap.put(Integer.valueOf(979), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("TJ");
            hashMap2.put("TJ", Integer.valueOf(992));
            hashMap.put(Integer.valueOf(992), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("TM");
            hashMap2.put("TM", Integer.valueOf(993));
            hashMap.put(Integer.valueOf(993), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("AZ");
            hashMap2.put("AZ", Integer.valueOf(994));
            hashMap.put(Integer.valueOf(994), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("GE");
            hashMap2.put("GE", Integer.valueOf(995));
            hashMap.put(Integer.valueOf(995), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("KG");
            hashMap2.put("KG", Integer.valueOf(996));
            hashMap.put(Integer.valueOf(996), arrayList);
            arrayList = new ArrayList(1);
            arrayList.add("UZ");
            hashMap2.put("UZ", Integer.valueOf(998));
            hashMap.put(Integer.valueOf(998), arrayList);
            sCountryCodeToRegionCodeMap = hashMap;
            sRegionCodeToCountryCodeMap = hashMap2;
        }
    }
}
