package com.facebook.feed.logging.impression;

/* compiled from: invalidation_behavior */
public enum FeedUnitImpressionType {
    VIEWPORT_IMPRESSION,
    VIEWPORT_DURATION_IMPRESSION,
    SPONSORED_DURATION_IMPRESSION,
    SPONSORED_IMPRESSION,
    ORGANIC_IMPRESSION,
    NON_VIEWABILITY_IMPRESSION,
    NON_SPONSORED_IMPRESSION,
    FEED_UNIT_HEIGHT,
    FEED_UNIT_SEEN,
    FEED_UNIT_STORY_MSG_LENGTH,
    SPONSORED_PERCENT_UNIT_SEEN,
    SPONSORED_FULL_VIEW_IMPRESSION
}
