package com.facebook.messaging.inbox2.items;

/* compiled from: mRemoteFetchDelayIntervalMillis must be >= 0 */
public enum InboxItemType {
    V2_RECENT_THREADS_PLACEHOLDER,
    V2_THREAD,
    V2_CONVERSATION_STARTER,
    V2_PEOPLE_YOU_MAY_MESSAGE,
    V2_PEOPLE_YOU_MAY_MESSAGE_USER,
    V2_SECTION_HEADER,
    V2_MESSAGE_REQUEST_HEADER,
    V2_ACTIVE_NOW,
    V2_ACTIVE_NOW_LOADING,
    V2_ACTIVE_NOW_EMPTY_ITEM,
    V2_RECENT_VIDEOS,
    V2_RECENT_VIDEO,
    V2_RECENT_LINKS,
    V2_RECENT_LINK,
    V2_RTC_RECOMMENDATION,
    V2_TRENDING_GIFS,
    V2_TRENDING_GIF_ITEM,
    V2_CAMERA_ROLL,
    V2_CAMERA_ROLL_ITEM,
    V2_LOAD_MORE_THREADS_PLACEHOLDER,
    V2_MONTAGE_COMPOSER_HEADER,
    V2_PHOTO_REMINDERS,
    V2_BYMM,
    V2_MORE_FOOTER,
    V2_MESSAGE_REQUEST_THREADS,
    V2_ANNOUNCEMENT,
    V2_UNKNOWN_TYPE
}
