package com.facebook.graphql.model.conversion;

import com.facebook.graphql.model.GraphQLMedia;
import com.facebook.graphql.model.GraphQLPhoto;
import com.facebook.graphql.model.GraphQLPhoto.Builder;
import com.facebook.graphql.model.GraphQLVideo;
import javax.annotation.Nullable;

/* compiled from: bytes= */
public final class GraphQLMediaConversionHelper {
    @Nullable
    public static GraphQLPhoto m235a(@Nullable GraphQLMedia graphQLMedia) {
        if (graphQLMedia == null || graphQLMedia.j() == null || graphQLMedia.j().g() != 77090322) {
            return null;
        }
        Builder builder = new Builder();
        builder.d = graphQLMedia.k();
        builder.e = graphQLMedia.l();
        builder.g = graphQLMedia.m();
        builder.h = graphQLMedia.n();
        builder.i = graphQLMedia.o();
        builder.j = graphQLMedia.p();
        builder.k = graphQLMedia.r();
        builder.l = graphQLMedia.s();
        builder.m = graphQLMedia.t();
        builder.n = graphQLMedia.u();
        builder.o = graphQLMedia.v();
        builder.p = graphQLMedia.w();
        builder.q = graphQLMedia.x();
        builder.r = graphQLMedia.y();
        builder.s = graphQLMedia.A();
        builder.t = graphQLMedia.B();
        builder.u = graphQLMedia.D();
        builder.v = graphQLMedia.E();
        builder.w = graphQLMedia.F();
        builder.y = graphQLMedia.G();
        builder.z = graphQLMedia.H();
        builder.A = graphQLMedia.I();
        builder.B = graphQLMedia.J();
        builder.C = graphQLMedia.L();
        builder.D = graphQLMedia.O();
        builder.E = graphQLMedia.P();
        builder.F = graphQLMedia.b();
        builder.G = graphQLMedia.S();
        builder.I = graphQLMedia.T();
        builder.J = graphQLMedia.U();
        builder.M = graphQLMedia.V();
        builder.N = graphQLMedia.W();
        builder.O = graphQLMedia.X();
        builder.P = graphQLMedia.Y();
        builder.S = graphQLMedia.Z();
        builder.V = graphQLMedia.bq();
        builder.X = graphQLMedia.aa();
        builder.Y = graphQLMedia.ab();
        builder.Z = graphQLMedia.ac();
        builder.aa = graphQLMedia.ad();
        builder.ab = graphQLMedia.ae();
        builder.ac = graphQLMedia.bt();
        builder.ae = graphQLMedia.ai();
        builder.ag = graphQLMedia.aj();
        builder.ah = graphQLMedia.bx();
        builder.ai = graphQLMedia.ak();
        builder.aj = graphQLMedia.an();
        builder.ak = graphQLMedia.ar();
        builder.al = graphQLMedia.as();
        builder.an = graphQLMedia.at();
        builder.ao = graphQLMedia.au();
        builder.ap = graphQLMedia.aw();
        builder.aq = graphQLMedia.ay();
        builder.as = graphQLMedia.az();
        builder.au = graphQLMedia.aA();
        builder.av = graphQLMedia.aB();
        builder.aw = graphQLMedia.aC();
        builder.ax = graphQLMedia.aD();
        builder.ay = graphQLMedia.aE();
        builder.aA = graphQLMedia.aF();
        builder.aB = graphQLMedia.aG();
        builder.aC = graphQLMedia.aH();
        builder.aD = graphQLMedia.aI();
        builder.aE = graphQLMedia.aK();
        builder.aF = graphQLMedia.aL();
        builder.aG = graphQLMedia.aM();
        builder.aH = graphQLMedia.aN();
        builder.aI = graphQLMedia.aO();
        builder.aJ = graphQLMedia.aQ();
        builder.aK = graphQLMedia.aR();
        builder.aM = graphQLMedia.aS();
        builder.aQ = graphQLMedia.aT();
        builder.aR = graphQLMedia.aW();
        builder.aS = graphQLMedia.aZ();
        builder.aT = graphQLMedia.ba();
        builder.aU = graphQLMedia.bh();
        builder.aV = graphQLMedia.bk();
        builder.aX = graphQLMedia.bn();
        builder.aY = graphQLMedia.bp();
        return builder.a();
    }

    @Nullable
    public static GraphQLVideo m236b(@Nullable GraphQLMedia graphQLMedia) {
        if (graphQLMedia == null || graphQLMedia.j() == null || graphQLMedia.j().g() != 82650203) {
            return null;
        }
        GraphQLVideo.Builder builder = new GraphQLVideo.Builder();
        builder.f = graphQLMedia.m();
        builder.g = graphQLMedia.n();
        builder.h = graphQLMedia.o();
        builder.i = graphQLMedia.p();
        builder.j = graphQLMedia.q();
        builder.k = graphQLMedia.r();
        builder.l = graphQLMedia.br();
        builder.n = graphQLMedia.t();
        builder.o = graphQLMedia.y();
        builder.p = graphQLMedia.z();
        builder.q = graphQLMedia.C();
        builder.t = graphQLMedia.E();
        builder.u = graphQLMedia.F();
        builder.w = graphQLMedia.G();
        builder.y = graphQLMedia.I();
        builder.z = graphQLMedia.K();
        builder.A = graphQLMedia.M();
        builder.B = graphQLMedia.N();
        builder.C = graphQLMedia.O();
        builder.D = graphQLMedia.P();
        builder.F = graphQLMedia.Q();
        builder.G = graphQLMedia.R();
        builder.H = graphQLMedia.b();
        builder.I = graphQLMedia.S();
        builder.J = graphQLMedia.T();
        builder.K = graphQLMedia.U();
        builder.L = graphQLMedia.V();
        builder.M = graphQLMedia.W();
        builder.N = graphQLMedia.X();
        builder.O = graphQLMedia.Y();
        builder.P = graphQLMedia.Z();
        builder.Q = graphQLMedia.bq();
        builder.R = graphQLMedia.aa();
        builder.S = graphQLMedia.ab();
        builder.T = graphQLMedia.ac();
        builder.U = graphQLMedia.ad();
        builder.V = graphQLMedia.ae();
        builder.X = graphQLMedia.bt();
        builder.Y = graphQLMedia.af();
        builder.Z = graphQLMedia.ag();
        builder.aa = graphQLMedia.ah();
        builder.ab = graphQLMedia.ai();
        builder.ac = graphQLMedia.aj();
        builder.ad = graphQLMedia.ak();
        builder.ae = graphQLMedia.by();
        builder.ag = graphQLMedia.al();
        builder.ah = graphQLMedia.am();
        builder.ai = graphQLMedia.an();
        builder.aj = graphQLMedia.ao();
        builder.ak = graphQLMedia.ap();
        builder.al = graphQLMedia.aq();
        builder.am = graphQLMedia.as();
        builder.an = graphQLMedia.at();
        builder.ao = graphQLMedia.au();
        builder.aq = graphQLMedia.av();
        builder.ar = graphQLMedia.ax();
        builder.as = graphQLMedia.ay();
        builder.at = graphQLMedia.az();
        builder.av = graphQLMedia.aA();
        builder.aw = graphQLMedia.aB();
        builder.ax = graphQLMedia.aC();
        builder.az = graphQLMedia.aD();
        builder.aA = graphQLMedia.aE();
        builder.aB = graphQLMedia.aF();
        builder.aC = graphQLMedia.aJ();
        builder.aE = graphQLMedia.aK();
        builder.aF = graphQLMedia.aL();
        builder.aG = graphQLMedia.aM();
        builder.aH = graphQLMedia.aN();
        builder.aI = graphQLMedia.aO();
        builder.aL = graphQLMedia.aP();
        builder.aM = graphQLMedia.aQ();
        builder.aN = graphQLMedia.bz();
        builder.aO = graphQLMedia.aR();
        builder.aY = graphQLMedia.aU();
        builder.aZ = graphQLMedia.aV();
        builder.ba = graphQLMedia.aW();
        builder.be = graphQLMedia.aX();
        builder.bf = graphQLMedia.aY();
        builder.bg = graphQLMedia.bs();
        builder.bh = graphQLMedia.bb();
        builder.bi = graphQLMedia.bc();
        builder.bj = graphQLMedia.bd();
        builder.bk = graphQLMedia.be();
        builder.bl = graphQLMedia.bf();
        builder.bn = graphQLMedia.bg();
        builder.bo = graphQLMedia.bw();
        builder.bp = graphQLMedia.bh();
        builder.bq = graphQLMedia.bi();
        builder.br = graphQLMedia.bj();
        builder.bs = graphQLMedia.bv();
        builder.bw = graphQLMedia.bA();
        builder.bz = graphQLMedia.bl();
        builder.bB = graphQLMedia.bm();
        builder.bC = graphQLMedia.bn();
        builder.bE = graphQLMedia.bu();
        builder.bI = graphQLMedia.bo();
        return builder.a();
    }
}
