package com.facebook.abtest.qe.bootstrap.autoqe;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Target({ElementType.TYPE})
@Retention(RetentionPolicy.SOURCE)
/* compiled from: translation_confidence */
public @interface AutoGeneratedQESpec {
}
