package com.facebook.graphql.model.conversion;

import com.facebook.graphql.enums.GraphQLObjectType;
import com.facebook.graphql.model.GraphQLMedia;
import com.facebook.graphql.model.GraphQLMedia$Builder;
import com.facebook.graphql.model.GraphQLPhoto;
import javax.annotation.Nullable;

/* compiled from: TT;)V */
public final class GraphQLPhotoConversionHelper {
    @Nullable
    public static GraphQLMedia m22613a(GraphQLPhoto graphQLPhoto) {
        GraphQLMedia$Builder graphQLMedia$Builder = new GraphQLMedia$Builder();
        graphQLMedia$Builder.f4452d = graphQLPhoto.j();
        graphQLMedia$Builder.f4453e = graphQLPhoto.k();
        graphQLMedia$Builder.f4454f = graphQLPhoto.m();
        graphQLMedia$Builder.f4455g = graphQLPhoto.n();
        graphQLMedia$Builder.f4456h = graphQLPhoto.o();
        graphQLMedia$Builder.f4457i = graphQLPhoto.p();
        graphQLMedia$Builder.f4459k = graphQLPhoto.q();
        graphQLMedia$Builder.f4461m = graphQLPhoto.r();
        graphQLMedia$Builder.f4462n = graphQLPhoto.s();
        graphQLMedia$Builder.f4463o = graphQLPhoto.t();
        graphQLMedia$Builder.f4464p = graphQLPhoto.u();
        graphQLMedia$Builder.f4465q = graphQLPhoto.v();
        graphQLMedia$Builder.f4466r = graphQLPhoto.w();
        graphQLMedia$Builder.f4467s = graphQLPhoto.x();
        graphQLMedia$Builder.f4469u = graphQLPhoto.y();
        graphQLMedia$Builder.f4470v = graphQLPhoto.z();
        graphQLMedia$Builder.f4472x = graphQLPhoto.A();
        graphQLMedia$Builder.f4473y = graphQLPhoto.B();
        graphQLMedia$Builder.f4474z = graphQLPhoto.C();
        graphQLMedia$Builder.f4426A = graphQLPhoto.D();
        graphQLMedia$Builder.f4427B = graphQLPhoto.E();
        graphQLMedia$Builder.f4428C = graphQLPhoto.F();
        graphQLMedia$Builder.f4429D = graphQLPhoto.G();
        graphQLMedia$Builder.f4431F = graphQLPhoto.H();
        graphQLMedia$Builder.f4434I = graphQLPhoto.I();
        graphQLMedia$Builder.f4435J = graphQLPhoto.J();
        graphQLMedia$Builder.f4438M = graphQLPhoto.K();
        graphQLMedia$Builder.f4439N = graphQLPhoto.L();
        graphQLMedia$Builder.f4440O = graphQLPhoto.N();
        graphQLMedia$Builder.f4441P = graphQLPhoto.O();
        graphQLMedia$Builder.f4442Q = graphQLPhoto.R();
        graphQLMedia$Builder.f4443R = graphQLPhoto.S();
        graphQLMedia$Builder.f4444S = graphQLPhoto.T();
        graphQLMedia$Builder.f4445T = graphQLPhoto.U();
        graphQLMedia$Builder.f4446U = graphQLPhoto.X();
        graphQLMedia$Builder.f4447V = graphQLPhoto.aZ();
        graphQLMedia$Builder.f4448W = graphQLPhoto.ab();
        graphQLMedia$Builder.f4449X = graphQLPhoto.ac();
        graphQLMedia$Builder.f4450Y = graphQLPhoto.ad();
        graphQLMedia$Builder.f4451Z = graphQLPhoto.ae();
        graphQLMedia$Builder.aa = graphQLPhoto.af();
        graphQLMedia$Builder.ab = graphQLPhoto.ba();
        graphQLMedia$Builder.af = graphQLPhoto.ah();
        graphQLMedia$Builder.ag = graphQLPhoto.aj();
        graphQLMedia$Builder.ah = graphQLPhoto.bb();
        graphQLMedia$Builder.ai = graphQLPhoto.ak();
        graphQLMedia$Builder.am = graphQLPhoto.al();
        graphQLMedia$Builder.aq = graphQLPhoto.am();
        graphQLMedia$Builder.ar = graphQLPhoto.an();
        graphQLMedia$Builder.as = graphQLPhoto.ap();
        graphQLMedia$Builder.at = graphQLPhoto.aq();
        graphQLMedia$Builder.av = graphQLPhoto.ar();
        graphQLMedia$Builder.ax = graphQLPhoto.as();
        graphQLMedia$Builder.ay = graphQLPhoto.au();
        graphQLMedia$Builder.az = graphQLPhoto.aw();
        graphQLMedia$Builder.aA = graphQLPhoto.ax();
        graphQLMedia$Builder.aB = graphQLPhoto.ay();
        graphQLMedia$Builder.aC = graphQLPhoto.az();
        graphQLMedia$Builder.aD = graphQLPhoto.aA();
        graphQLMedia$Builder.aE = graphQLPhoto.aB();
        graphQLMedia$Builder.aF = graphQLPhoto.aC();
        graphQLMedia$Builder.aG = graphQLPhoto.aD();
        graphQLMedia$Builder.aH = graphQLPhoto.aE();
        graphQLMedia$Builder.aJ = graphQLPhoto.aF();
        graphQLMedia$Builder.aK = graphQLPhoto.aG();
        graphQLMedia$Builder.aL = graphQLPhoto.aH();
        graphQLMedia$Builder.aM = graphQLPhoto.aI();
        graphQLMedia$Builder.aN = graphQLPhoto.aJ();
        graphQLMedia$Builder.aP = graphQLPhoto.aK();
        graphQLMedia$Builder.aR = graphQLPhoto.aL();
        graphQLMedia$Builder.aS = graphQLPhoto.aN();
        graphQLMedia$Builder.aT = graphQLPhoto.aR();
        graphQLMedia$Builder.aW = graphQLPhoto.aS();
        graphQLMedia$Builder.aZ = graphQLPhoto.aT();
        graphQLMedia$Builder.ba = graphQLPhoto.aU();
        graphQLMedia$Builder.bj = graphQLPhoto.aV();
        graphQLMedia$Builder.bn = graphQLPhoto.aW();
        graphQLMedia$Builder.br = graphQLPhoto.bc();
        graphQLMedia$Builder.bu = graphQLPhoto.aY();
        graphQLMedia$Builder.bv = new GraphQLObjectType(77090322);
        return graphQLMedia$Builder.m9005a();
    }
}
