package com.facebook.graphql.model.conversion;

import com.facebook.graphql.enums.GraphQLObjectType;
import com.facebook.graphql.model.GraphQLMedia;
import com.facebook.graphql.model.GraphQLMedia$Builder;
import com.facebook.graphql.model.GraphQLVideo;
import javax.annotation.Nullable;

/* compiled from: TT; */
public final class GraphQLVideoConversionHelper {
    @Nullable
    public static GraphQLMedia m22615a(GraphQLVideo graphQLVideo) {
        GraphQLMedia$Builder graphQLMedia$Builder = new GraphQLMedia$Builder();
        graphQLMedia$Builder.f4454f = graphQLVideo.k();
        graphQLMedia$Builder.f4455g = graphQLVideo.o();
        graphQLMedia$Builder.f4456h = graphQLVideo.p();
        graphQLMedia$Builder.f4457i = graphQLVideo.q();
        graphQLMedia$Builder.f4458j = graphQLVideo.r();
        graphQLMedia$Builder.f4459k = graphQLVideo.s();
        graphQLMedia$Builder.f4460l = graphQLVideo.t();
        graphQLMedia$Builder.f4462n = graphQLVideo.u();
        graphQLMedia$Builder.f4467s = graphQLVideo.v();
        graphQLMedia$Builder.f4468t = graphQLVideo.w();
        graphQLMedia$Builder.f4471w = graphQLVideo.x();
        graphQLMedia$Builder.f4473y = graphQLVideo.y();
        graphQLMedia$Builder.f4474z = graphQLVideo.z();
        graphQLMedia$Builder.f4426A = graphQLVideo.A();
        graphQLMedia$Builder.f4428C = graphQLVideo.l();
        graphQLMedia$Builder.f4430E = graphQLVideo.C();
        graphQLMedia$Builder.f4432G = graphQLVideo.D();
        graphQLMedia$Builder.f4433H = graphQLVideo.E();
        graphQLMedia$Builder.f4434I = graphQLVideo.F();
        graphQLMedia$Builder.f4435J = graphQLVideo.G();
        graphQLMedia$Builder.f4436K = graphQLVideo.H();
        graphQLMedia$Builder.f4437L = graphQLVideo.I();
        graphQLMedia$Builder.f4438M = graphQLVideo.J();
        graphQLMedia$Builder.f4439N = graphQLVideo.K();
        graphQLMedia$Builder.f4440O = graphQLVideo.L();
        graphQLMedia$Builder.f4441P = graphQLVideo.M();
        graphQLMedia$Builder.f4442Q = graphQLVideo.N();
        graphQLMedia$Builder.f4443R = graphQLVideo.O();
        graphQLMedia$Builder.f4444S = graphQLVideo.P();
        graphQLMedia$Builder.f4445T = graphQLVideo.Q();
        graphQLMedia$Builder.f4446U = graphQLVideo.R();
        graphQLMedia$Builder.f4447V = graphQLVideo.bx();
        graphQLMedia$Builder.f4448W = graphQLVideo.S();
        graphQLMedia$Builder.f4449X = graphQLVideo.T();
        graphQLMedia$Builder.f4450Y = graphQLVideo.U();
        graphQLMedia$Builder.f4451Z = graphQLVideo.V();
        graphQLMedia$Builder.aa = graphQLVideo.W();
        graphQLMedia$Builder.ab = graphQLVideo.bF();
        graphQLMedia$Builder.ac = graphQLVideo.Y();
        graphQLMedia$Builder.ad = graphQLVideo.Z();
        graphQLMedia$Builder.ae = graphQLVideo.aa();
        graphQLMedia$Builder.af = graphQLVideo.ab();
        graphQLMedia$Builder.ag = graphQLVideo.ac();
        graphQLMedia$Builder.ai = graphQLVideo.ad();
        graphQLMedia$Builder.aj = graphQLVideo.bK();
        graphQLMedia$Builder.ak = graphQLVideo.ae();
        graphQLMedia$Builder.al = graphQLVideo.af();
        graphQLMedia$Builder.am = graphQLVideo.ag();
        graphQLMedia$Builder.an = graphQLVideo.ah();
        graphQLMedia$Builder.ao = graphQLVideo.ai();
        graphQLMedia$Builder.ap = graphQLVideo.aj();
        graphQLMedia$Builder.ar = graphQLVideo.ak();
        graphQLMedia$Builder.as = graphQLVideo.al();
        graphQLMedia$Builder.at = graphQLVideo.am();
        graphQLMedia$Builder.au = graphQLVideo.ao();
        graphQLMedia$Builder.aw = graphQLVideo.ap();
        graphQLMedia$Builder.ax = graphQLVideo.aq();
        graphQLMedia$Builder.ay = graphQLVideo.ar();
        graphQLMedia$Builder.az = graphQLVideo.as();
        graphQLMedia$Builder.aA = graphQLVideo.at();
        graphQLMedia$Builder.aB = graphQLVideo.au();
        graphQLMedia$Builder.aC = graphQLVideo.aw();
        graphQLMedia$Builder.aD = graphQLVideo.ax();
        graphQLMedia$Builder.aE = graphQLVideo.ay();
        graphQLMedia$Builder.aI = graphQLVideo.az();
        graphQLMedia$Builder.aJ = graphQLVideo.aA();
        graphQLMedia$Builder.aK = graphQLVideo.aB();
        graphQLMedia$Builder.aL = graphQLVideo.aC();
        graphQLMedia$Builder.aM = graphQLVideo.aD();
        graphQLMedia$Builder.aN = graphQLVideo.aE();
        graphQLMedia$Builder.aO = graphQLVideo.aH();
        graphQLMedia$Builder.aP = graphQLVideo.aI();
        graphQLMedia$Builder.aQ = graphQLVideo.bM();
        graphQLMedia$Builder.aR = graphQLVideo.aJ();
        graphQLMedia$Builder.aU = graphQLVideo.aT();
        graphQLMedia$Builder.aV = graphQLVideo.aU();
        graphQLMedia$Builder.aW = graphQLVideo.aV();
        graphQLMedia$Builder.aX = graphQLVideo.aY();
        graphQLMedia$Builder.aY = graphQLVideo.aZ();
        graphQLMedia$Builder.bb = graphQLVideo.bE();
        graphQLMedia$Builder.bc = graphQLVideo.ba();
        graphQLMedia$Builder.bd = graphQLVideo.bb();
        graphQLMedia$Builder.be = graphQLVideo.bc();
        graphQLMedia$Builder.bf = graphQLVideo.bd();
        graphQLMedia$Builder.bg = graphQLVideo.be();
        graphQLMedia$Builder.bh = graphQLVideo.bf();
        graphQLMedia$Builder.bi = graphQLVideo.bH();
        graphQLMedia$Builder.bj = graphQLVideo.bg();
        graphQLMedia$Builder.bk = graphQLVideo.bh();
        graphQLMedia$Builder.bl = graphQLVideo.bi();
        graphQLMedia$Builder.bm = graphQLVideo.bG();
        graphQLMedia$Builder.bo = graphQLVideo.bN();
        graphQLMedia$Builder.bp = graphQLVideo.bo();
        graphQLMedia$Builder.bq = graphQLVideo.bp();
        graphQLMedia$Builder.br = graphQLVideo.bq();
        graphQLMedia$Builder.bs = graphQLVideo.bs();
        graphQLMedia$Builder.bt = graphQLVideo.bw();
        graphQLMedia$Builder.bv = new GraphQLObjectType(82650203);
        return graphQLMedia$Builder.m9005a();
    }
}
