package com.facebook.omnistore.module;

import com.facebook.inject.AutoGeneratedBinder;

@AutoGeneratedBinder
/* compiled from: text_color */
public final class AutoGeneratedBindingsForOmnistoreModule {
}
