package com.facebook.friending.center.constants;

/* compiled from: fontStyle */
public enum FriendsCenterSource {
    CI_PROMOTION_EMPTY_FEED,
    FEED_PYMK,
    FIND_FRIENDS_BOOKMARK,
    FRIEND_REQUEST_TRAY_NOTIFICATION,
    FRIENDS_BOOKMARK,
    FRIENDS_TAB_SEE_ALL_PYMK,
    FRIENDS_TAB_SPROUT_LAUNCHER,
    NOTIFICATIONS_FRIENDING_TAB_FIND_FRIENDS,
    NOTIFICATIONS_FRIENDING_TAB_SEE_ALL_FRIEND_REQUESTS,
    TIMELINE_ABOUT_FRIENDS_APP,
    TIMELINE_PENDING_REQUESTS_PROMPT,
    TIMELINE_PYMK,
    REACTION_FRIEND_REQUESTS_CARD
}
